services:
  - type: web
    name: bitget-tracker
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: "10000"
      - key: TRADERS
        value: "DKTrading:1443199880395776000,XauKingScalp:1433276980578508800,FutureTrader:1427930164156649472:futures"
      - key: POLL_INTERVAL_SEC
        value: "30"
